### ISSUE TITLE
【編集画面】複数ページへの対応

### ISSUE THREAD

**Issue by g-Ratie** [AllenShintani/Skalp_AI#57]

**Comment by AllenShintani** [comment]
これはスライドページ作成のISSUEの続きの内容かな？

**Comment by g-Ratie** [comment]
そうです
手が空いたらやろうとしてたんだけど、よく考えたら前回時点で完了してた気がするからCloseしておきます

**Comment by AllenShintani** [comment]
@g-Ratie 
これまだ完了していなくない？
複数のスライドとテキストボックスの管理はまだできていないのでは

**Comment by g-Ratie** [comment]
こないだの作業内で終わってると勘違いしてました
データ構造も変えたことだし、改めてこっちでやりますね
