### ISSUE TITLE
【編集画面】要素のサイズによって中央ガイドがズレる

### ISSUE THREAD

**Issue by g-Ratie** [AllenShintani/Skalp_AI#73]
要素を大きくすると中央線のガイドがズレる
(テキストボックスでも発生する)

https://github.com/AllenShintani/Skalp_AI/assets/36080294/9fbaf22c-8b68-44ea-9ecd-875d71b737bb

**Comment by AllenShintani** [comment]
あら、本当や

**Comment by skmtrd** [comment]
私担当します

**Comment by skmtrd** [comment]
feature/#54時点(画像の一番下のプッシュ)でまだ大丈夫そうなので、画像にも補助線が出るようにしたときにロジックが変わっちゃったんですかね。

https://github.com/AllenShintani/Skalp_AI/assets/167765460/677e52db-64f1-4d9f-b341-5e0c08599889
![スクリーンショット 2024-06-19 075303](https://github.com/AllenShintani/Skalp_AI/assets/167765460/74b6927e-cdfc-4394-9dbb-246a70e1a543)

**Comment by skmtrd** [comment]
修正しました。カスタムフックにするときにロジックが書き換わってました。。。なぜですかね。
あと自分のほうだと画像に対しては補助線出なかったんですけど、ラティさん実装途中だったりしますかね？
https://github.com/AllenShintani/Skalp_AI/assets/167765460/54ef86b1-fc56-4c61-8aed-39f8c9d35e58

**Comment by skmtrd** [comment]
修正中に発見したんですけどリサイズもバグリ散らかしている、、、右下にしか引っ張らないから気づかれてなかったのかな、、、

https://github.com/AllenShintani/Skalp_AI/assets/167765460/0363dd69-6be1-4645-86c9-b3dd5d43e326

**Comment by AllenShintani** [comment]
...今日テストコードについて話します

**Comment by g-Ratie** [comment]
> 修正しました。カスタムフックにするときにロジックが書き換わってました。。。なぜですかね。 あと自分のほうだと画像に対しては補助線出なかったんですけど、ラティさん実装途中だったりしますかね？ https://github.com/AllenShintani/Skalp_AI/assets/167765460/54ef86b1-fc56-4c61-8aed-39f8c9d35e58

#57 で画像にもカスタムフックを適応しました
